#!/usr/bin/env bash
# A script to transfer a file to a server
##########################################

if [ $# -lt 4 ];
then
	echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit(1)
fi

file_path=$1
ip=$2
user=$3
ssh_key_path=$4

scp -o StrictHostKeyChecking=no -i "$ssh_key_path" "$file_path" "$user@$ip:~/"
