#!/usr/bin/env bash
# Install Nginx on a server with a page that displays "hello World"

sudo apt-get update
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
sudo ufw reload
sudo rm /var/www/html/*
sudo touch /var/www/html/welcome.html
sudo chown $USER /var/www/html/welcome.html
echo "<h1>Hello World!</h1>" > /var/www/html/welcome.html
