#!/usr/bin/env bash 
# installs nginx and configure it to listen on port 80 
# print "Hello World" 
 
sudo apt-get -y update 
sudo apt-get -y install nginx 
echo 'Hello World!' > /var/www/html/index.nginx-debian.html 
sed -i '/listen 80 default_server;/a \\trewrite ^/redirect_me$ http://github.com/Ambrosekol permanent;/' /etc/nginx/sites-available/default 
sudo service nginx restart
