#!/usr/bin/bash
# this installs and configures haproxy on a new machine

sudo apt-get -y update
sudo apt install -y haproxy=1.6.\*

echo '
frontend ambrosekol.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 64820-web-01 100.26.152.157:80
        server 64820-web-02 52.86.102.6:80
' >> /etc/haproxy/haproxy.cfg

# restart tha haproxy service
service haproxy restart
