#!/usr/bin/env bash
# this installs and configures haproxy on a new machine

sudo apt-get -y update
sudo apt-get -y install haproxy=1.6.\*

echo "
frontend ambrosekol.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 357270-web-01 52.91.135.166:80
        server 357270-web-02 54.237.41.50:80
" >> /etc/haproxy/haproxy.cfg

# restart tha haproxy service
service haproxy restart
