#!/usr/bin/env bash
# fixes Nginx to listen on port 80
apt-get -y update
apt-get -y install nginx
service nginx start
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo sed -i "/server_name _;/ a\\\trewrite ^/redirect_me https://github.com/ambrosekol permanent;" /etc/nginx/sites-available/default
sudo sed -i "s/listen/listen 80 default_server;" /etc/nginx/sites-enabled/default
service nginx restart
