#!/usr/bin/env bash
# Write a Bash script that displays a list of currently running processes.
#
#			Requirements:
#
# - Must show all processes, for all users, including those which might not have a TTY
# - Display in a user-oriented format
# - Show process hierarchy
######################################################################################

echo "USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND"

# Get all processes with their hierarchies using 'ps' command
ps -eo user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,command
