#!/usr/bin/env bash
# Bash script that configures an Ubuntu server
####################################

if [ $EUID -ne 0 ]
then
	exit 1
fi

cp /etc/hosts ~/hosts.new
sed "127.0.0.2 localhost" ~/hosts.new
sed "8.8.8.8 facebook.com" ~/hosts.new
cp -f ~/hosts.new /etc/hosts
