#!/usr/bin/env bash
# Script to display total addresses (IPV 4)
###############################################

ipv4_addresses=$(ip -4 addr | grep -oP '(?<=inet\s)\d+(\.\d+){3}')
echo ipc4_addresses
